import Head from "next/head";
import Image from "next/image";
import { DM_Sans } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import { useRef, useState } from "react";
import QRCode from "react-qr-code";

const dmsans = DM_Sans({ subsets: ["latin"] });
function toTitleCase(str) {
  return str.replace(
    /\w\S*/g,
    (text) => text.charAt(0).toUpperCase() + text.substring(1).toLowerCase()
  );
}
export default function Home() {
  const [name, setName] = useState("");
  const nameInputRef = useRef();
  return (
    <>
      <Head>
        <title>boo!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${dmsans.className}`}>
        <QRCode
          value={`https://www.paarthkukreja.com/${
            name ? `?to=${toTitleCase(name.replace(" ", "%20"))}` : ""
          }`}
        ></QRCode>
        <br />
        <br />
        <input
          type="text"
          value={name}
          className={styles.nameInput}
          placeholder="enter your name"
          ref={nameInputRef}
          onChange={(e) => {
            setName(e.target.value);
          }}
        />
        <div
          onClick={() => {
            setName("");
            nameInputRef.current.focus();
          }}
          className={styles.resetButtonCont}
        >
          <p className={styles.resetButton}>reset</p>
        </div>
        {/* <div className={styles.generateButton}>Generate QR Code</div> */}
      </main>
    </>
  );
}
